server:  port: 80
spring:
  mvc:
      view:
        suffix: .jsp
        prefix: /WEB-INF/jsp/
      thymeleaf:
        cache: false
        enabled: false
  resources:
      static-locations: classpath:/WEB-INF/resources