server:
  port: 80
app:
  serverUrl: http://122.51.69.242
  teplateAuthSuccessMsg: URxUnbbPIuj099nVL1cjgAw49IQnFmcaPTo7irDZjrY
  tulingKey: f0d99d4e9fc44ec096afdf510c575437
  tulingAPI: http://www.tuling123.com/openapi/api?key=%s&info=%s
  
  mobileQueryAPI: https://tcc.taobao.com/cc/json/mobile_tel_segment.htm?tel=%s
  
  weatherQueryKey: 9c6cffd8234b72883c8eb29dafaf1186
  weatherQueryAPI: http://apis.juhe.cn/simpleWeather/query?city=%s&key=%s
  
  jokeKey: adfcb4c94398b302dc292480c603e461
  jokeAPI: http://japi.juhe.cn/joke/content/list.from?sort=desc&page=1&pagesize=5&time=%s&key=%s
  
  idcardKey: 71d491b10a631f771ca2c41e1e538ce8
  idcardAPI: http://apis.juhe.cn/idcard/index?key=%s&cardno=%s
  
  hisTodayKey: 30fea9d48adbf81fc86713f5333f8701
  hisTodayAPI: http://api.juheapi.com/japi/toh?key=%s&v=1.0&month=%s&day=%s
spring:
  application:
    name: wx-walk
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cd-cdb-4tlk3omc.sql.tencentcdb.com:62785/wxWalk?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwer9527
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

wx:
  mp:
    appId: wx0985b6dbaeeff28c
    config-storage:
      redis:
        host: 127.0.0.1
        port: 6379
      type: redis
    secret: d3ba2d045ffc578abd0e9d23f8c93404
    token: imook
  pay:
    appId: wx4492fde581248a1d
    mchId: 1512382871
    mchKey: 1492b9eb24ac067333d714412dd591d1
    
mybatis:
  type-aliases-package: com.starter.domain
  mapper-locations: classpath:mapper/*.xml
  
baidu:
  api:
    mapAk: gYPKBfcQee3nAx5jx71VxiBHyl0EbRKT
    mapUrlPlaceSearch: http://api.map.baidu.com/place/v2/search?query=%s&location=%s&radius=2000&output=xml&ak=%s
    mapUrlGetLocation: http://api.map.baidu.com/geocoder?location=%s&output=json&key=%s
    mapConvertUrl: http://api.map.baidu.com/ag/coord/convert?from=2&to=4&x=%s&y=%s
    
    transApiUrl: http://api.fanyi.baidu.com/api/trans/vip/translate?q=%s&from=auto&to=%s&appid=%s&salt=%s&sign=%s
    transAppid: 20170322000042938
    transSecurityKey: xHp5E7D0ULLkVT2Ac3Xg
    
file:
  path: /home/uploads/