spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
  port: 80
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: F://日志
#  file: F://日志/sell.log
#  level:
#    com.imooc.LoggerTest: debug

# 下面是微信相关的配置
wechat:
#  mpAppId: wxdcf91e9f784bfad0
#  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268 #测试号appId,appSecret
  mpAppId: wx0985b6dbaeeff28c
  mpAppSecret: d3ba2d045ffc578abd0e9d23f8c93404 #借用号appId,appSecret
  token: imook
  openAppId: wx4492fde581248a1d
  openAppSecret: a5a91cdbc9b737b028e8bd95d7ed65c0 #开放平台测试号appId,appSecret
  #openAppId: wx0985b6dbaeeff28c
  #openAppSecret: d3ba2d045ffc578abd0e9d23f8c93404 #借用帐号appId,appSecret
  mchId: 1512382871
  mchKey: 577b4caef339121384314f827350cf5c
  keyPath: C:/Users/Administrator/Downloads/h5.p12
  notifyUrl: http://ssxzrm.natappfree.cc/notify
  templateId:
    orderStatus: GoCullfix05R-rCibvoyI87ZUg50cyieKA5AyX7pPzo

projectUrl:
  wechatMpAuthorize: http://ssxzrm.natappfree.cc
  wechatOpenAuthorize: http://ssxzrm.natappfree.cc
  sell: http://ssxzrm.natappfree.cc
